openapi: 3.0.0

servers:
  - url: localhost:8080/

info: 
  version: "2.2.0"
  title: EyeConnection APIs

tags:
  - name: user
    description: Available to users
  - name: doctor
    description: Available to doctors
  - name: system
    description: Available to system

paths:
  /sign_up:
    post:
      description: create new users in system
      tags: 
      - user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: example@email.com
                password:
                  type: string
                  example: password123
                lastName:
                  type: string
                  example: White
                firstName:
                  type: string
                  example: Mike
                zipCode:
                  type: integer
                  example: 10011
        required: true
      responses:
        "201":
          description: successfully created new user
        "202":
          description: created new user failed

  /user_log_in:
    post:
      description: users log into system
      tags: 
      - user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: example@email.com
                password:
                  type: string
                  example: password123
        required: true
      responses:
        "200":
          description: successfully log in
        "401":
          description: log in failed
  
  /make_appointment:
    post:
      description: a patient make an appointment with a doctor
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                patient_sys_id:
                  type: number
                  example: 912239
                doctor_sys_id:
                  type: number
                  example: 912233
                appointment_date:
                  example: "2023-01-01 13:00"
                online:
                  type: boolean
                  example: true
      responses:
        "201":
          description: make an appointment successfully
        "202":
          description: make an appointment failed
  
  /doctor_log_in:
    post:
      description: users log into system
      tags: 
      - doctor
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: example@email.com
                password:
                  type: string
                  example: password123
        required: true
      responses:
        "200":
          description: successfully log in
        "401":
          description: log in failed
  
  /update_available_dates:
    put:
      description: update available time for doctors
      tags:
      - doctor
      requestBody:
        content:
          application/json:
            schema:
              properties:
                doctor_sys_id: 
                  type: number
                  example: 930233
                dates:
                  type: array
                  example: ["2023-03-20 12:00", "2023-03-21 13:00"]
      responses:
        "200":
          description: update available time successfully

  /confirm_appointment:
    put:
      description: confirm appointment request
      tags: 
      - doctor
      requestBody:
        content:
          application/json:
           schema:
            properties:
              appointment_id:
                type: number
                example: 123456
              appointment_status:
                type: string
                example: Approved
              online_meeting:
                type: string
                example: "https://zoom.us/13edfeerc"
              notes:
                type: string
                example: "No eating after 8:00 PM"
      responses:
        "200":
          description: confirm appointment successfully

  /search_by_condition:
    post:
      description: user search available doctors according to conditions
      tags:
      - system
      requestBody:
        content:
          application/json:
            schema:
              properties:
                city:
                  type: string
                  example: Boston
                state:
                  type: string
                  example: MA
                zip_code:
                  type: integer
                  example: 10011
                category:
                  type: string
                  example: Dentist
                support_online:
                  type: boolean
                  example: true
                available_date:
                  example: "2015-03-01 12:00"
      responses:
        "200":
          description: results of user search
          content: 
            application/json:
              schema:
                properties:
                  doctors_list:
                    type: array
                    items:
                      type: object
                      properties:
                        email:
                          type: string
                        last_name:
                          type: string
                        first_name:
                          type: string
                        rate:
                          type: integer
                        address:
                          type: string
                        city:
                          type: string
                        state:
                          type: string
                        available_date:
                          type: array
                        role:
                          type: string
                        portrait:
                          type: string
                        support_online:
                          type: boolean
                    example:
                      - email: green.white@gmail.com
                        last_name: white
                        first_name: green
                        rate: 5.0
                        address: 101th Street, Building 1
                        city: Boston
                        state: MA
                        available_date: ["2023-01-01 13:00", "2023-02-02 13:00"]
                        role: Dentist
                        portrait: "/portrait_img/Ek2789fbh"
                        support_online: true
                      - email: david.wang@gmail.com
                        last_name: wang
                        first_name: david
                        rate: 4.1
                        address: 11th Street, Building 2
                        city: Boston
                        state: MA
                        available_date: ["2023-01-01 13:00", "2023-02-02 13:00"]
                        role: Optometryist
                        portrait: "/portrait_img/AKING2877"
                        support_online: false

  /create_notification:
    post:
      description: push a notification to the taget user or doctor according to the sys_id
      tags: 
      - system
      requestBody:
        content:
            application/json:
              schema:
                properties:
                  notification_id:
                    type: number
                    example: 010002981
                  sender_sys_id:
                    type: number
                    example: 3990181
                  receiver_sys_id:
                    type: number
                    example: 93884829
                  message:
                    type: object
                    example: {
                      title: Appointment updated,
                      content: Appointment(299032) status has been updated by Dr. White,
                      time: "2016-01-03 19:00"
                    }
                  unread:
                    type: boolean
                    example: true
      responses:
          "201":
            description: create a notification successfully

  /all_appointments?sysid={sysid}:
    get:
      description: show all appointments
      parameters:
      - in: path
        name: sysid
        schema:
          type: number
        required: true
      tags:
      - system
      responses:
        "200":
          description: show appointment information
          content: 
            application/json:
              schema:
                properties:
                  appointments:
                    type: array
                    example: ["appointment1", "appointment2", "appointment3"]

  /appointment_detail?appointment_id={appointment_id}:
    get:
      description: show appointment details
      parameters:
      - in: path
        name: appointment_id
        schema:
          type: number
        required: true
      tags:
      - system
      responses:
        "200":
          description: show appointment details
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/appointment'

  /profile?sysid={sysid}&type={type}:
    get:
      description: get profile information for rendering
      parameters:
      - in: path
        name: sysid
        schema:
          type: number
        required: true
      - in: path
        name: type
        schema:
          type: number
        description: determine what type of sys_id (doctor or user)
        required: true
      tags:
      - system
      responses:
        "200":
          description: show profile information
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                    example: green@gmail.com
                  lastName:
                    type: string
                    example: White
                  firstName:
                    type: string
                    example: Mike
                  portrait:
                    type: string
                    example: "/green-wiley-portrait"
  
  /get_notification?sysid={sysid}:
    get:
      description: get notification for user or doctor with sysid
      parameters:
      - in: path
        name: sysid
        schema:
          type: number
        required: true
      tags:
        - system
      responses:
        "200":
          description: get notification successfully
          content:
            application/json:
              schema:
                properties:
                  notification_id:
                      type: number
                      example: 010002981
                  sender_sys_id:
                    type: number
                    example: 3990181
                  receiver_sys_id:
                    type: number
                    example: 93884829
                  message:
                    type: object
                    example: {
                      title: Appointment updated,
                      content: Appointment(299032) status has been updated by Dr. White,
                      time: "2016-01-03 19:00"
                    }
                  unread:
                    type: boolean
                    example: true

  /get_available_dates?doctor_sys_id={doctor_sys_id}:
    get:
      description: get available dates of a doctor with sysid
      parameters:
      - in: path
        name: doctor_sys_id
        schema:
          type: number
        required: true
      tags:
        - system
      responses:
        "200":
          description: get notification successfully
          content:
            application/json:
              schema:
                properties:
                  doctor_sys_id:
                      type: number
                      example: 010002981
                  available_dates:
                      type: array
                      example: ["2016-01-03 13:00", "2016-01-05 09:00"]

  /update_appointment_status:
    put:
      description: update the status of an appointment
      tags:
      - system
      requestBody:
        content:
          application/json:
            schema:
              properties:
                appointment_id:
                  type: number
                  example: 930233
                new_status:
                  type: string
                  example: Canceled
      responses:
        "204":
          description: update the status successfully

components:
  schemas:
    user:
      properties:
        sys_id:
          type: integer
          example: 22
        email:
          type: string
          example: example@email.com
        password:
          type: string
          example: password123
        last_name:
          type: string
          example: White
        first_name:
          type: string
          example: Mike
        zipCode:
          type: integer
          example: 10011

    doctor:
      properties:
        sys_id:
          type: string
          example: 0023AET9
        email:
          type: string
          example: example@email.com
        phone:
          type: string
          example: 110-123-4567
        password:
          type: string
          example: password123
        last_name:
          type: string
          example: Green
        first_name:
          type: string
          example: Wiley
        zip_code:
          type: integer
          example: 10011
        rate:
          type: integer
          example: 4.8
        address:
          type: string
          example: 106th Street, Building 1st
        city:
          type: string
          example: Boston
        state:
          type: string
          example: MA
        role:
          type: string
          example: Dentist
        portrait:
          type: string
          example: "/green-wiley-portrait"
        support_online:
          type: boolean
          example: true
    
    appointment:
      properties:
        appointment_id:
          type: number
          example: 123456
        doctor_sys_id: 
          type: number
          example: 930233
        patient_sys_id:
          type: number
          example: 930235
        appointment_status:
          type: string
          example: Finished, Pending, Approved, Cancelled, Aborted
        online:
          type: boolean
          example: true
        online_meeting:
          type: string
          example: "https://zoom.us/13edfeerc"
        appointment_date:
          example: "2023-01-03 13:00"
        notes:
          type: string
          example: "No eating after 8:00 PM"
    
    available_dates:
      properties:
        id:
          type: number
          example: 10
        doctor_sys_id:
          type: number
          example: 0137819
        available_date:
          example: "2023-01-03 13:00"

    notifications:
      properties:
        notification_id:
          type: number
          example: 123456
        sender_sys_id:
          type: number
          example: 232428
        receiver_sys_id:
          type: number
          example: 2324398
        message:
          type: string
          example: {
            'title': 'Appointment updated',
            'content': 'Your application has been updated, doctor approved your request',
            'time': '2023-01-03 13:00'
          }
        unread:
          type: boolean
          example: true