package com.eyeconnection.server.enums;

public enum DoctorRoles {
    DENTIST,
    PSYCHOLOGIST,
    DERMATOLOGIST,
    PHARMACIST,
    CARDIOLOGIST,
    UROLOGIST,
    ENDOCRINOLOGIST,
    PEDIATRICIAN,
    NEUROLOGIST,
    OBSTETRICIANS,
    GYNECOLOGISTS,
    OPTOMETRIST,
    PODIATRIST,
    LAB,
    CANCER
}
